# version: 2.1
# jobs:
#   say-hello:
#     environment:
#       vietnv17: FPTSOFTWARE
#       mssv: 17
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#             # - build/*
#       - run:
#           name: "Say hello"
#           command:  "echo Hello0000000000! > text.txt"
#       - run:
#           name: "variable"
#           command: |
#             VAR_0='Rasperi Pi'
#             echo my variable $vietnv17 $VAR_0
#       - persist_to_workspace:
#           root: .
#           paths:
#             - .
#   say-World:
#     environment:
#       pipeline_id: <<pipeline.id>>
#       mssv: 17
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - attach_workspace:
#           at: .
#       - run:
#           name: "pipeline_id"
#           command: "echo $pipeline_id"
#       - run:
#           name: test pwd cmd
#           command:     pwd
#       - run:
#           name: test ls cmd
#           command:     ls
#       - run:
#           name: "Say world"
#           command: cat text.txt
# workflows:
#   say-hello-workflow:
#     jobs:
#       - say-hello
#           # requires: 
#           #   - say-World
#       - say-World:
#           requires:
#             - say-hello


# 
# 
# 
# COMMANDS  & Anchor
# 
# 
# 
version: 2.1


parameters:
  myParameter:
    type: string
    default: "default value"
  anotherParameter:
    type: boolean
    default: false


commands:
  on-job-fail:
    description: "Only run when any Job fail"
    steps:
      - run:
          name: On job fail
          command: echo "Job fail"
          when: on_fail
  say-hello-command:
    description: "Prints 'Hello' to the console"
    steps:
      - run:
          name: Say Hello
          command: echo "Hello"


# Define an anchor for the common steps
anchors:
  common_docker: &common_docker
    docker:
          - image: cimg/base:stable
        
  common_steps: &common_steps
    checkout

jobs:
  say-hello:
    # Reference the common docker anchor
    <<: *common_docker
    # Additional steps specific to this job
    steps:
    # Reference the common steps anchor
      -  *common_steps
      - say-hello-command
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Failure Step
          command: exit 1
      - on-job-fail

workflows:
  say-hello-workflow:
    jobs:
      - say-hello